seed: 0
optimizer: rs
search_space: nasbench101
dataset: cifar10
out_dir: run_search

sample_from_valids: True
graph_features_pickle_path: "../../../../../zc_combine/data/nasbench101-cifar10.pickle"
graph_features_model: rf
valid_networks: "../../../../../zc_combine/data/nb101_nets.csv"

is_search: True

search:
  seed: 0
  checkpoint_freq: 1000
  epochs: 100
  fidelity: -1

  predictor_type: graph_features_xgb_params
  num_init: 10  
  k: 10

  # BANANAS
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: random_sampling
  encoding_type: adjacency_one_hot
  num_arches_to_mutate: 2
  max_mutations: 1
  num_candidates: 20
  
  # jacov data loader
  batch_size: 256
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7
  
  # other params
  debug_predictor: False
  sample_size: 10
  population_size: 30
